M48
; DRILL file {KiCad 7.0.7} date Wed Oct  2 11:43:49 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-02T11:43:49-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X3.9146Y-1.5699
X6.2756Y-1.5769
T2
X3.178Y-3.708
T0
M30
